const ACTION_TYPES = {
    GET_INPUT_DETAILS: 'GET_INPUT_DETAILS',
    SET_OUTPUT_DETAILS: 'SET_OUTPUT_DETAILS',
    GET_CHALLENGE_DETAILS: 'GET_CHALLENGE_DETAILS',
    GET_MOVIES_DETAILS: 'GET_MOVIES_DETAILS'
};

export {
    ACTION_TYPES
}